
export const skillset=[
    "Algorithms", 
"Analytical Skills", 
"Big Data", 
"Calculating", 
"Compiling Statistics", 
"Data Analytics", 
"Data Mining", 
"Database Design", 
"Database Management", 
"Documentation", 
"Modeling", 
"Modification", 
"Needs Analysis", 
"Quantitative Research", 
"Quantitative Reports", 
"Statistical Analysis", 
"Applications", 
"Certifications", 
"Coding", 
"Computing", 
"Configuration", 
"Customer Support", 
"Debugging", 
"Design", 
"Development", 
"Hardware", 
"Implementation", 
"Information Technology", 
"ICT", 
"Infrastructure", 
"Languages", 
"Maintenance", 
"Network Architecture", 
"Network Security", 
"Networking", 
"New Technologies", 
"Operating Systems", 
"Programming", 
"Restoration", 
"Security", 
"Servers", 
"Software", 
"Solution Delivery", 
"Storage", 
"Structures", 
"Systems Analysis", 
"Technical Support", 
"Technology", 
"Testing", 
"Tools", 
"Training", 
"Troubleshooting", 
"Usability", 
"Benchmarking", 
"Budget Planning", 
"Engineering", 
"Fabrication", 
"Following Specifications", 
"Operations", 
"Performance Review", 
"Project Planning", 
"Quality Assurance", 
"Quality Control", 
"Scheduling", 
"Task Delegation", 
"Task Management", 
"Content Management Systems (CMS)", 
"Blogging", 
"Digital Photography", 
"Digital Media", 
"Search Engine Optimization (SEO)", 
"Information Security", 
"Microsoft Office Certifications", 
"Video Creation", 
"Customer Relationship Management (CRM)", 
"Productivity Software", 
"Cloud/SaaS Services", 
"Database Management", 
"Telecommunications", 
"Human Resources Software", 
"Accounting Software", 
"Enterprise Resource Planning (ERP) Software", 
"Database Software", 
"Query Software", 
"Blueprint Design", 
"Medical Billing", 
"Medical Coding", 
"Sonography", 
"Structural Analysis", 
"Artificial Intelligence (AI)", 
"Mechanical Maintenance", 
"Manufacturing", 
"Inventory Management", 
"Numeracy", 
"Information Management", 
"Hardware Verification Tools and Techniques", 
"Hardware Description Language (HDL)", 
"Marketing", 
"Area Operations Manager", 
"Building Operations Manager", 
"Business Operations", 
"Computer Operations Manager", 
"Data Operations Manager", 
"Division Manager", 
"Equipment Technician", 
"Gas Operations", 
"General Manager Operations", 
"Maintenance Assistant", 
"Manager - Operations", 
"Manufacturer", 
"Manufacturing", 
"Materials Manager", 
"National Operations Manager", 
"Network Operations", 
"Operations Assistant", 
"Operations Control Manager", 
"Operations Development Manager", 
"Operations Director", 
"Operations Leader", 
"Operations Leadership Development Program", 
"Operations Management", 
"Operations Manager I", 
"Operations Planning Manager", 
"Operations Shift Manager", 
"Operations Shift Supervisor", 
"Operations Staff", 
"Production", 
"Production Management", 
"Production Manager", 
"Quality Assurance", 
"Quality Control Manager", 
"Safety Manager", 
"Sales Operations Manager", 
"Service Operations Manager", 
"Store Operations Manager", 
"Strategy And Operations Manager", 
"Technician", 
"Analyst", 
"Bank Assistant", 
"Bank Employee", 
"Bank Manager", 
"Credit Manager", 
"Finance Associate", 
"Finance Business Manager", 
"Finance Department", 
"Financial", 
"Financial Accounting", 
"Financial Aid", 
"Financial Analysis Manager", 
"Financial Director", 
"Financial Executive", 
"Financial Leadership Development Program", 
"Financial Management", 
"Financial Manager", 
"Financial Operations", 
"Financial Planning", 
"Financial Planning Manager", 
"Financial Professional", 
"Financial Relationship Manager", 
"Financial Reporting", 
"Financial Representative", 
"Financial Research", 
"Financial Service Associate", 
"Financial Service Representative", 
"Financial Services", 
"Financial Services Manager", 
"Financial Services Professional", 
"Financial Services Sales Agents", 
"Industry Analyst", 
"Investment Professional", 
"IT Finance Manager", 
"Project Finance", 
"Project Management", 
"Revenue Management", 
"Revenue Manager", 
"Senior Financial Manager", 
"Tax", 
"Assembly", 
"Building Maintenance", 
"Construction", 
"Construction Engineering Manager", 
"Construction Managers", 
"Construction Project Engineer", 
"Construction Project Manager", 
"Construction Services Manager", 
"Development Officer", 
"Equipment Operator", 
"Facilities Assistant", 
"Facilities Director", 
"Facilities Maintenance Supervisor", 
"Facilities Maintenance Technician", 
"Facilities Managers", 
"Field Service Technician", 
"General Maintenance Technician", 
"Head Of Facilities", 
"Housekeeping", 
"Hvac", 
"Hvac Technician", 
"Mail Carrier", 
"Maintenance Manager", 
"Maintenance Mechanic", 
"Maintenance Person", 
"Maintenance Supervisor", 
"Maintenance Technician", 
"Maintenance Worker", 
"Mechanic", 
"Medical", 
"Medical Technology", 
"Picker", 
"Plant Manager", 
"Production Associate", 
"Service Advisor", 
"Service Coordinator", 
"Service Specialist", 
"Telecom", 
"Telecommunication", 
"select state", 
"    Computer", 
"    Corporate IT", 
"    Development", 
"    Group IT Manager", 
"    Information Technology", 
"    IT Applications Development", 
"    IT Assistant", 
"    IT Compliance Manager", 
"    IT Contractor", 
"    IT Department", 
"    IT Department Manager", 
"    IT Development", 
"    IT Director", 
"    IT Employee", 
"    IT Expert", 
"    IT Leader", 
"    IT Management", 
"    IT Manager", 
"    IT Operations Manager", 
"    IT Position", 
"    IT Professional", 
"    IT Program Manager", 
"    IT Project Manager", 
"    IT Recruiter", 
"    IT Resource Manager", 
"    IT Security", 
"    IT Security Manager", 
"    IT Specialist", 
"    IT Staff", 
"    IT Supervisor", 
"    IT System Manager", 
"    IT Team Lead", 
"    IT Technician", 
"    IT Technology", 
"    IT Worker", 
"    Senior IT", 
"    Student IT", 
"    Technical Support", 
"    Technology", 
"    Web", 
"   Assistant Professor - Communication", 
"    Assistant Professor Communication", 
"    Assistant Professor Communication Journalism", 
"    Assistant Professor Communication Studies", 
"    Broadband Technician", 
"    Communication", 
"    Communication Designer", 
"    Communication Director", 
"    Communication Executive", 
"    Communication Officer", 
"    Communication Specialist", 
"    Corporate Communication Executive", 
"    Data Communication Analyst", 
"    Digital Communication Manager", 
"    Senior Telecom Analyst", 
"    Telecom Analyst", 
"    Telecom Business Analyst", 
"    Telecom Tech", 
"    Telecommunications Administrator", 
"    Telecommunications Coordinator", 
"    Telecommunications Director", 
"    Telecommunications Field Service Technician", 
"    Telecommunications Network Analyst", 
"    Telecommunications Officer", 
"    Telecommunications Operator", 
"    Telecommunications Project Manager", 
"    Telecommunications Supervisor", 
"    Telecommunications Systems Analyst", 
"    Telecommunications Technician", 
"    Telephony Engineer", 
"    Visual Communication Designer", 
"    Wireless Consultant", 
"Assistant Store Manager", 
"Associate Product Manager", 
"Associate Store Manager", 
"Cashier", 
"Display Manager", 
"Night Manager", 
"Retail", 
"Retail Area Manager", 
"Retail Assistant", 
"Retail Assistant Manager", 
"Retail Assistant Store Manager", 
"Retail Business Manager", 
"Retail Cashier", 
"Retail Department Manager", 
"Retail Lead", 
"Retail Sales", 
"Retail Sales Assistant", 
"Retail Sales Lead", 
"Retail Sales Manager", 
"Retail Sales Professional", 
"Retail Sales Representative", 
"Retail Sales Supervisor", 
"Retail Store Associate", 
"Retail Store Manager", 
"Retail Store Team Leader", 
"Retail Supervisor", 
"Stock Associate", 
"Store Assistant", 
"Store Associate", 
"Store Employee", 
"Store Lead", 
"Store Management", 
"Store Manager", 
"Store Model", 
"Store Person", 
"Store Personnel", 
"Store Supervisor", 
"Store Team Lead", 
"Store Team Leader", 
"Adjuster", 
"Automotive Mechanic", 
"Cable Installer", 
"Cnc Machine Operator", 
"Cnc Programmer", 
"Electro Mechanical Technician", 
"Emergency Management Specialist", 
"Locksmith", 
"Machine Builder", 
"Maintenance Planner", 
"Mechanical Drafter", 
"Process Technician", 
" Assistant Legal Cashier", 
"Assistant Manager Legal", 
"Attorney", 
"Attorney At Law", 
"Company Lawyer", 
"Corporate Attorney", 
"Director Legal Affairs", 
"Employment Law Advocate", 
"Family Law Attorney", 
"General Counsel", 
"Head Of Legal Department", 
"International Law Consultant", 
"Law Associate", 
"Law Clerk", 
"Law Intern", 
"Law Student", 
"Legal", 
"Legal Administrative Assistant", 
"Legal Advisor", 
"Legal Advocate", 
"Legal Assistant", 
"Legal Assistant I", 
"Legal Assistant Office Manager", 
"Legal Associate", 
"Legal Compliance Officer", 
"Legal Consultant", 
"Legal Director", 
"Legal Officer", 
"Legal Practitioner", 
"Legal Research Associate", 
"Legal Secretary", 
"Litigation Associate", 
"Litigation Attorney", 
"Manager Legal Affairs", 
"Paralegal", 
"Private Client Legal Executive", 
"Real Estate Attorney", 
"Senior Legal Counsel", 
"Tax Attorney", 
"Vice President Legal", 
" Benefits Administrator", 
"Benefits Manager", 
"Benefits Specialist", 
"Claim Advisor", 
"Claims Adjuster", 
"Claims Assistant", 
"Commercial Insurance Agent", 
"Commercial Insurance Producer", 
"Credit Risk Analyst", 
"Field Investigator", 
"Independent Insurance Agent", 
"Inspector", 
"Insurance", 
"Insurance Adjuster", 
"Insurance Administrator", 
"Insurance Advisor", 
"Insurance Agency Manager", 
"Insurance Agent", 
"Insurance Agents Office Manager", 
"Insurance Assistant", 
"Insurance Broker", 
"Insurance Clerk", 
"Insurance Consultant", 
"Insurance Coordinator", 
"Insurance Processor", 
"Insurance Professional", 
"Insurance Sales", 
"Insurance Sales Executive", 
"Insurance Sales Representative", 
"Insurance Underwriter", 
"Insurance Verification", 
"Insurance Verification Specialist", 
"Investigator", 
"Lead Asset Protection Associate", 
"Life Insurance Agent", 
"Life Insurance Specialist", 
"Nationwide Insurance", 
"Pricing Analyst", 
"Quality Assurance Technician", 



"    Agency Recruiter", 
"    Area Human Resources Manager", 
"    Contract Recruiter", 
"    Employment Recruiter", 
"    Head Of HR", 
"    HR Associate", 
"    HR Manager", 
"    HR Partner", 
"    HR Personnel", 
"    HR Supervisor", 
"    Human Resources Benefits Manager", 
"    Human Resources Department", 
"    Human Resources Employee", 
"    Human Resources Management", 
"    Human Resources Operations", 
"    Human Resources Partner", 
"    Human Resources Program Manager", 
"    Human Resources Project Manager", 
"    Human Resources Recruiting", 
"    Human Resources Services", 
"    Human Resources Staff", 
"    Human Resources Technician", 
"    Job Coach", 
"    Lead Recruiter", 
"    National Recruiter", 
"    Professional Recruiter", 
"IT recruiter", 
"Non IT recruiter", 
"    Recruiter", 
"    Recruiting Assistant", 
"    Recruiting Associate", 
"    Recruiting Director", 
"    Recruiting Manager", 
"    Recruiting Supervisor", 
"    Recruitment Associate", 
"    Recruitment Director", 
"    Recruitment Lead", 
"    Recruitment Partner", 
"    Recruitment Professional", 
"    Regional Recruiter", 
"    Technical Recruiter", 
"    Us Recruiter", 
" Assistant Food Service Manager", 
"Assistant General Manager", 
"Assistant Restaurant Manager", 
"Bar Manager", 
"Barista", 
"Chef", 
"Cook", 
"Cook Fast Food", 
"Cooking", 
"Dishwasher", 
"Fast Food Restaurant Manager", 
"Fast Food Worker", 
"Food And Beverage", 
"Food And Beverage Manager", 
"Food Manager", 
"Food Prep", 
"Food Safety Manager", 
"Food Server", 
"Food Service", 
"Food Service Associate", 
"Food Service Cashier", 
"Food Service Representative", 
"Food Service Supervisor", 
"Food Service Worker", 
"Food Supervisor", 
"Food Worker", 
"Hospitality", 
"Host", 
"Kitchen Help", 
"Kitchen Manager", 
"Kitchen Staff", 
"Line Cook", 
"Prep Cook", 
"Restaurant", 
"Restaurant General Manager", 
"Restaurant Management", 
"Restaurant Manager", 
"Restaurant Worker", 
"Server", 

" Assistant Professor Medicine", 
"Certified Pharmacy Tech", 
"Certified Pharmacy Technician", 
"Clinical Research Associate", 
"Clinical Staff Pharmacist", 
"Director Of Pharmacy", 
"Director Of Pharmacy Services", 
"Drug Safety Associate", 
"Emergency Medicine Resident", 
"Family Medicine Resident", 
"Internal Medicine Physician", 
"Internal Medicine Resident", 
"Lab Assistant", 
"Lab Technician", 
"Laboratory Manager", 
"Lead Pharmacist", 
"Pharmaceutical Analyst", 
"Pharmaceutical Business Development Manager", 
"Pharmaceutical Sales Manager", 
"Pharmaceutical Technician", 
"Pharmacist", 
"Pharmacist I", 
"Pharmacist Manager", 
"Pharmacist Technician", 
"Pharmacy", 
"Pharmacy Associate", 
"Pharmacy Cashier", 
"Pharmacy Resident", 
"Pharmacy Student", 
"Pharmacy Technician", 
"Physician (family Medicine)", 
"Physician (internal Medicine)", 
"Physician - Internal Medicine", 
"Physician Occupational Medicine", 
"Physician Sports Medicine", 
"Physician- Internal Medicine", 
"Professor Medicine", 
"Ptcb Pharmacy Technician", 
"Registered Pharmacist", 
"Retail Pharmacist", 
"    Accounting Contractor", 
"    Art", 
"    Art Assistant", 
"    Art Director", 
"    Art Manager", 
"    Art Specialist", 
"    Arts And Entertainment", 
"    Audio Video", 
"    Design Manager", 
"    Designer", 
"    Development Director", 
"    Editor", 
"    Electrical Contractor", 
"    Entertainment", 
"    Entertainment Manager", 
"    Factory Manager", 
"    Fashion", 
"    Film", 
"    Freelance", 
"    General Contractor", 
"    Graphic Designer", 
"    Illustrator", 
"    Independent Contractor", 
"    Journalism", 
"    Media", 
"    Music", 
"    News Analyst", 
"    News Producer", 
"    Private Contractor", 
"    Publishing Manager", 
"    Record Label", 
"    Reporter", 
"    Scheduling Coordinator", 
"    Senior Designer", 
"    Sound Engineer", 
"    Stage Manager", 
"    Sub Contractor", 
"    Ui Designer", 
"    User Interface Designer", 
"    Writer", 


" Administration", 
"Administration Manager", 
"Administrative Assist", 
"Administrative Assistance", 
"Administrative Assistant", 
"Administrative Service Manager", 
"Administrative Staff", 
"Administrative Support", 
"Assistant Manager", 
"Banking", 
"Billing", 
"Business Administration", 
"Clerical", 
"Clerk Of Works", 
"Customer Service Administrative", 
"Data Entry", 
"District Manager", 
"Executive Director", 
"Freight Team", 
"Inventory", 
"Inventory Management", 
"IT Administrative", 
"Office Administration", 
"Office Administrative", 
"Office Assistant", 
"Office Management", 
"Operator", 
"Payroll", 
"Payroll Manager", 
"Personal Assistant", 
"Personnel Administration", 
"Post Office", 
"Program Coordinator", 
"Project Administrative", 
"Purchasing Manager", 
"Receiving Associate", 
"Sales Administrative", 
"Shipping", 
"Telephone", 
"Warehouse", 
" Account", 
"Account Development", 
"Account Development Manager", 
"Account Lead", 
"Account Management", 
"Account Management Representative", 
"Account Manager - Sales", 
"Account Operations Manager", 
"Account Service", 
"Account Service Manager", 
"Account Service Representative", 
"Account Supervisor", 
"Accounting And Finance", 
"Accounting Manager", 
"Audit", 
"Budget Manager", 
"Business Account Executive", 
"Business Account Manager", 
"Business Development Account Manager", 
"Cna", 
"Cost Accounting", 
"Customer Account Executive", 
"Customer Account Manager", 
"Customer Account Representative", 
"Education Account Manager", 
"Finance Manager", 
"Financial Account Manager", 
"Financial Associate", 
"Financial Reporting Manager", 
"Internal Account Manager", 
"IT Sales Account Manager", 
"Key Account", 
"Key Account Sales", 
"Lead Account Manager", 
"Manager Account Management", 
"Marketing Account Manager", 
"New Business Account Manager", 
"Partner Account Manager", 
"Retail Account Manager", 
"Sales Account", 
" Captain", 
"Completions Supervisor", 
"Dc Power Engineer", 
"Electrical Power Engineer", 
"Energy Advisor", 
"Energy Analyst", 
"Energy Broker", 
"Energy Coordinator", 
"Energy Engineer", 
"Energy Expert", 
"Energy Management Systems Engineer", 
"Energy Manager", 
"Energy Market Analyst", 
"Energy Modeling Engineer", 
"Energy Sales Advisor", 
"Energy Sales Consultant", 
"Energy Systems Engineer", 
"Engineer Electrical Power Systems", 
"Engineers Power Distribution", 
"Environmental Advisor", 
"Environmental Coordinator", 
"Environmental Manager", 
"Power Electronics", 
"Power Electronics Engineer", 
"Power Market Analyst", 
"Power Plant Engineer", 
"Power System Engineer", 
"Power Systems Control Engineer", 
"Renewable Energy Sales", 
"Safety Advisor", 
"Safety Consultant", 
"Safety Officer", 
"Safety Trainer", 
"Senior Energy Consultant", 
"Senior Energy Engineer", 
"Senior Power Electronics Engineer", 
"Senior Power Systems Engineer", 
"Software Specialist", 
"Waste Water", 
"Well Control Instructor", 
" Area Operations Manager", 
"Building Operations Manager", 
"Business Operations", 
"Computer Operations Manager", 
"Data Operations Manager", 
"Division Manager", 
"Equipment Technician", 
"Gas Operations", 
"General Manager Operations", 
"Maintenance Assistant", 
"Manager - Operations", 
"Manufacturer", 
"Manufacturing", 
"Materials Manager", 
"National Operations Manager", 
"Network Operations", 
"Operations Assistant", 
"Operations Control Manager", 
"Operations Development Manager", 
"Operations Director", 
"Operations Leader", 
"Operations Leadership Development Program", 
"Operations Management", 
"Operations Manager I", 
"Operations Planning Manager", 
"Operations Shift Manager", 
"Operations Shift Supervisor", 
"Operations Staff", 
"Production", 
"Production Management", 
"Production Manager", 
"Quality Assurance", 
"Quality Control Manager", 
"Safety Manager", 
"Sales Operations Manager", 
"Service Operations Manager", 
"Store Operations Manager", 
"Strategy And Operations Manager", 
"Technician", 
"Technology Operations Manager", 
" Acute Care Nurse", 
"Clinical Nurse", 
"Community Nurse", 
"Critical Care Nurse", 
"Critical Care Registered Nurse", 
"Dental", 
"Dental Associate", 
"Health", 
"Health And Safety Manager", 
"Health Assistant", 
"Health Care Assistant", 
"Health Care Manager", 
"Health Care Support", 
"Health Care Worker", 
"Health Information Manager", 
"Health Program Manager", 
"Health Services", 
"Health Services Managers", 
"Healthcare", 
"Healthcare Manager", 
"Healthcare Professional", 
"Healthcare Provider", 
"Home Health Nurse", 
"Hospital", 
"Lpn", 
"Lvn", 
"Medical Assistant", 
"Medical Manager", 
"Medical Nurse", 
"Medical Professional", 
"Medical Service Manager", 
"Medical Worker", 
"Nurse", 
"Nursing Assistant", 
"Physician", 
"Practice Nurse", 
"Registered Nurse", 
"Rn Nurse", 
"Therapist", 
"Travel Nurse", 
"    Associate Merchandise Planner", 
"    Book Buyer", 
"    Buyer I", 
"    Buying Assistant", 
"    Buying Director", 
"    Category Buyer", 
"    Corporate Buyer", 
"    Director Merchandise Planning", 
"    Distributor", 
"    Divisional Merchandise Manager", 
"    Fashion Buyer", 
"    Fashion Merchandiser", 
"    Field Merchandiser", 
"    General Merchandise Manager", 
"    Global Buyer", 
"    Head Of Buying", 
"    Lead Merchandiser", 
"    Materials Buyer", 
"    Merchandise Buyer", 
"    Merchandise Handler", 
"    Merchandise Planner", 
"    Merchandise Planning Manager", 
"    Merchandise Specialist", 
"    Merchandiser Manager", 
"    Online Merchandiser", 
"    Packaging Buyer", 
"    Part Time Merchandiser", 
"    Part-time Merchandiser", 
"    Print Buyer", 
"    Procurement Buyer", 
"    Product Merchandiser", 
"    Project Buyer", 
"    Pt Merchandiser", 
"    Purchasing Agent Buyer", 
"    Regional Merchandise Manager", 
"    Senior Merchandiser", 
"    Senior Project Buyer", 
"    Sourcing Buyer", 
"    Strategic Buyer", 
"    Talent Buyer", 
" Cdl Driver", 
"City Driver", 
"Class A Driver", 
"Class A Truck Driver", 
"Class Driver", 
"Company Driver", 
"Dedicated Driver", 
"Delivery", 
"Delivery Driver", 
"Driver", 
"Full Service Driver", 
"Inventory Manager", 
"Line Driver", 
"Local Driver", 
"Logistic", 
"Moving", 
"Otr Driver", 
"Otr Truck Driver", 
"Parts Driver", 
"Personal Driver", 
"Professional Driver", 
"Receiving", 
"Road Driver", 
"Route Driver", 
"Scheduling Manager", 
"Supply", 
"Supply Management", 
"Supply Manager", 
"Supply Supervisor", 
"Team Driver", 
"Test Driver", 
"Transport", 
"Transportation", 
"Transportation Driver", 
"Transportation Management", 
"Transportation Manager", 
"Truck Driver", 
"Ups Driver", 
"Warehouse Position",
"AngularJS", 
" ASCP", 
" Amazon Web Services", 
" Adjudication", 
" Aluminum", 
" Automated Testing", 

" Application Support", 
" Arenas", 
" Architecture Design", 
" Agility", 

" Advertisement", 

" Anesthesia", 
" Associate Engagement", 
" Access Control", 
" Arbor", 


" Autocad", 

" AI", 
" Applications Architecture", 
" Alcoholic Beverages", 
" Ancillary Services", 
" Apache", 
" Asset Protection", 


" AR", 
" Allied Health", 
" ARC", 
" Assembly Lines", 
" Aggregates", 
" Activate", 
" Animal", 
" Asset Management", 
" Author", 
" Architecting", 
" Applicant Tracking Systems", 
" Amenities", 
" Application Architecture", 
" Architects", 
" Accounting", 

" Appeals", 
" Animal Care", 
" Advanced Cardiac Life Support", 
" Apache Tomcat", 
" Artistry", 
" Arkansas", 
" Aspen", 
" Activities Of Daily Living", 
" Aggregation", 
" Advocacy", 
" Athletics", 
" Advisory Boards", 
" ANCC", 
" Ambulance", 
" ASI", 
" Agile", 
" Agile Software Development", 
" Aesthetics", 
" Agriculture", 
" Auditions", 
" Application Server", 
" Ajax", 
" ArcGIS", 
" Automation", 
" Automotive Parts", 
" ACE", 
" Accruals", 
" Artificial Intelligence", 
" ACH", 
" Autism Spectrum Disorders", 
" Abundance", 
" API Development", 
" Accident Insurance", 
" Adobe Photoshop", 

"    Behavioral Science", 
"     Bonus Programs", 
"     Buck", 
"     Building Maintenance", 
"     Business Services", 
"     Bread", 
"     Business Case", 
"     B2B", 
"     Bottles", 
"     B2C", 
"     Bias For Action", 
"     Business Development", 
"     BLAST", 
"     BREW", 
"     Business Intelligence", 
"     Buffet", 
"     Business Analytics", 
"     Business Ethics", 
"     Bowling", 
"     Bonds", 
"     Business Travel", 
"     Big Data", 
"     Big Box", 
"     Bids", 
"     Brewing", 
"     Bill Of Lading", 
"     Building Automation", 
"     Behavioral Health", 
"     Bank Reconciliation", 
"     Bill Of Materials", 
"     Baseball", 
"     Building Services", 
"     Behavior Management", 
"     Beacon", 
"     Business Insights", 
"     Blood Pressure", 
"     Biometrics", 
"     Bikes", 
"     Biotechnology", 
"     Bartending", 
"     Bearings", 
"     Business-to-Business", 
"     Budget Management", 
"     Biology", 
"     Batteries", 

"     Branding", 
"     Bulletins", 
"     Briefs", 
"     Business Analysis", 
"     Business Planning", 
"     Business Knowledge", 
"     Bridging", 
"     Boost", 
"     Building Materials", 
"     Budgeting", 

"     Baking", 
"     Broadband", 
"     Benchmarking", 
"     Birds", 
"     Booths", 
"     Black Belt", 
"     BET", 
"     Bipolar Disorder", 
"     Badges", 
"     Business Process", 
"     Belts", 
"     Brand Awareness", 
"     Brokerage", 
"     Boat", 
"     Bowman", 
"     Banners", 
"     Biochemistry", 
"     Boundary", 
"     Brand Management", 
"     Business Operations", 

"     Bioinformatics", 
"     Business Initiatives", 
     , 


"    CDA", 
"     CDC", 
"     Compilation", 
"     Community Engagement", 
"     Civil Rights", 
"     Cadence", 
"     CDL", 
"     Customer Loyalty", 
"     Conflict Resolution", 
"     CRM Software", 
"     CCNA", 
"     Cedar", 
"     Clinical Trials", 


"     Characterization", 
"     Capital Market", 
"     Checkout", 
"     Credit Reports", 
"     Counseling", 
"     Currency", 
"     CISSP", 
"     Cloth", 
"     Coronary", 
"     Coastal", 
"     Consumer Goods", 
"     Customer-focused", 
"     Clinical Documentation", 
"     Copying", 
"     Coordinate Meetings", 
"     Curriculum Vitae", 
"     Circuit", 
"     Code Review", 
"     CFCs", 
"     Crisis", 
"     Cables", 
"     Curriculum Development", 
"     C-Level", 
"     Corrective Maintenance", 
"     Continuous Monitoring", 
"     Continuous Integration", 
"     Civil Engineers", 
"     Cisco Certified", 
"     CCNP", 
"     C#", 
"     Change Requests", 
"     C", 
"     Consumer Privacy", 
"     Customer Satisfaction", 
"     Clean Rooms", 
"     Cash Advance", 
"     Contingency Plan", 
"     Credit Cards", 
"     CFR", 
"     Chairs", 
"     Comparison", 
"     Confluence", 
"     Credit Risk", 
"     Child Development", 
"     Community Health", 
"     Compliance Training", 
"     Customer Communication", 
"     Command And Control", 
"     Camping", 
"     Chart", 
"     Celebrations", 
"     Cranes", 
"     Cost Analysis", 
"     Counterintelligence", 
"     Clinical Operations", 
"     Center Of Excellence", 
"     Continuing Medical Education", 
"     Columns", 
"     Client Relations", 
"     Carbon", 
"     Critical Thinking", 
"     Cardiopulmonary Resuscitation", 
"     Crisis Management", 
"     Crowns", 
"     Cost Effective", 
     , 

" Dexterity", 
" Database Systems", 
" Development Tools", 
" Driving Results", 
" Detailing", 
" Difficult Situations", 
" Dispositions", 
" Department Of Transportation", 
" DNS", 
" Digital Transformation", 
" Disposal", 
" Data Sheets", 
" Docker", 
" Disciplinaries", 
" Department Stores", 
" Directives", 
" Disciplinary Action", 
" Data Architecture", 
" Data Governance", 
" Drug Testing", 
" Dialogues", 
" Decks", 
" Directing", 
" Data Entry", 
" Delaware", 
" Department Management", 
" Distributed Teams", 
" Dump", 
" Disease Management", 
" Decision-Making", 
" Demonstration", 
" Day Care", 
" Design-Build", 
" Demos", 
" Developmental Disabilities", 
" Drywall", 
" Disposables", 
" Diamonds", 
" Data Collection", 
" Desserts", 
" Data Center", 
" DHS", 
" Design Pattern", 
" Data Science", 
" Data Migration", 
" Document Control", 
" Does", 
" Devising", 
" DART", 
" Drilling", 
" Design Principles", 
" Data Lakes", 
" Direct Patient Care", 
" Direct Sales", 
" Debugging", 
" Disaster Recovery", 
" Dimension", 
" Dentistry", 
" Derivatives", 
" Deep Cleaning", 
" Dental Care", 
" Data Acquisition", 
" Dental Insurance", 
" Default", 
" Defense", 
" Deductive Reasoning", 
" Dresses", 
" Door To Door", 
" Dryers", 
" Defensive Driving", 
" DB2", 
" Downtime", 
" Data Analysis", 
" Dance", 
" Data Visualization", 
" Drive Results", 
" Data Security", 
" Drug Development", 
" Diabetes", 
" Differentiation", 

"    Emergency Situations", 
"     Eclipse", 
"     Electrical Controls", 
"     Extract", 
"     Elevators", 
"     Engineering Design", 
"     Encryption", 
"     Electrical Design", 
"     Environmental Protection", 
"     ElasticSearch", 
"     Earned Value Management", 
"     Event Management", 
"     Eagle", 
"     Expediting", 
"     Electrical Work", 
"     Etiquette", 
"     Emergency Medicine", 
"     Escrow", 
"     Enrollments", 
"     Engineering Management", 
"     Estimator", 
"     Enterprise Resource Planning", 
"     Electro-mechanical", 
"     Energy Efficiency", 
"     Enablement", 
"     Employee Engagement", 
"     Extracurricular Activities", 
"     Emotional Intelligence", 
"     Eclectic", 
"     External Agencies", 
"     ERP", 
"     Energy Management", 
"     ETL Tools", 
"     Elder Care", 
"     E-Learning", 
"     Errands", 
"     Executive Assistant", 
"     ESA", 
"     Enterprise Software", 
"     Exceptions", 
"     Emergency Procedures", 
"     Electrical Wiring", 
"     Espresso", 
"     Educational Materials", 
"     Entrepreneurship", 
"     Engineering Drawing", 
"     Equality And Diversity", 
"     ETL", 
"     ELD", 
"     Executive Leadership", 
"     Equipment Operation", 
"     Exceed Sales Goals", 
"     Environmental Services", 
"     Evidence-Based Practice", 
"     Elk", 
"     Estimating", 
"     Employment Verifications", 
"     Electronic Health Record", 
"     Elections", 
"     Engineering Support", 
"     Embedded System", 
"     Embedded Software", 
"     Emerging Technologies", 
"     Electronic Components", 
"     Employee Relations", 
"     E Agents", 
"     EDGE", 
"     Eras", 
"     Electrical Engineering", 
"     Economics", 
"     Emergency Services", 
"     Environmental Health", 
"     External Audit", 
"     EMS", 
"     External Clients", 
"     EMT", 
"     Equipment Installation", 
"     Ergonomics", 
"     Equities", 
"     Electrical Equipment", 
     , 


"    Food Manufacturing", 
"     FPGA", 
"     Financial Accounting", 
"     Folk", 
"     Financial Data", 
"     Field Service", 
"     Facilities Operations", 
"     Financial Support", 
"     Fixed Assets", 
"     Family Business", 
"     Federal And  Regulations", 
"     Fire Safety", 
"     FSA", 
"     Forwarding", 
"     Flooring", 
"     Field Work", 
"     Fixture", 
"     Field Support", 
"     Firmware", 
"     Fitch", 
"     Foster Care", 
"     Financial Management", 
"     Financial Performance", 
"     Fine Motor Skill", 
"     Financial Services", 
"     Food Safety", 
"     Fitness Center", 
"     Financial Plans", 
"     Fair Housing", 
"     Florida", 
"     Functional Testing", 
"     Florals", 
"     Following Procedures", 
"     Festivals", 
"     Fostering", 
"     Flex", 
"     Financial Transactions", 
"     Fabric", 
"     Food Preparation", 
"     Fiber Optics", 
"     Foreign Language", 
"     Fda", 
"     Food Quality", 
"     Fiduciary", 
"     Fire Alarm", 
"     Financial Futures", 
"     Fraud", 
"     FACT", 
"     Federal Government", 
"     Family Therapy", 
"     Financial Goals", 
"     Faith-based", 
"     French", 
"     Focal Point", 
"     Field Technicians", 
"     Fish", 
"     Financial Reports", 
"     Financial Model", 
"     Flynn", 
"     Fire Protection", 
"     Following Up", 
"     Fast Casual", 
"     Footwear", 
"     Fast Track", 
"     Failure Analysis", 
"     Functional Requirement", 
"     Fine Dining", 
"     Fms", 
"     Furnishings", 
"     Firewall", 
"     Fertilizers", 
"     Financial Modeling", 
"     FinTech", 
"     Frozen Food", 
"     Federal Law", 
"     Face-to-face", 
"     Front Desk", 
"     Food And Beverage", 
"     Film", 
"     Fountains", 
     , 


"    Geography", 
"     Gift Cards", 
"     Gutters", 
"     Group Therapy", 
"     Google Analytics", 
"     Gait", 
"     Genomics", 
"     Government Agencies", 
"     General Management", 
"     Global Delivery", 
"     Grinding", 
"     Gauges", 
"     Generally Accepted Accounting Principles", 
"     Graduate Students", 
"     Grinders", 
"     Green Cards", 
"     Grievances", 
"     GRASP", 
"     Geographic", 
"     Global Health", 
"     Good Manufacturing Practice", 
"     Glassware", 
"     GAAP", 
"     Generators", 
"     Geospatial", 
"     General Public", 
"     Geographic Information System", 
"     Git", 
"     Games", 
"     Glasses", 
"     Graduate Level", 
"     Growth Strategies", 
"     General Administrative", 
"     Georgia", 
"     Geriatrics", 
"     Gap Analysis", 
"     GitHub", 
"     Global Services", 
"     Glass", 
"     General Administration", 
"     Geometric", 
"     Group Meetings", 
"     Gigs", 
"     General Education", 
"     Gateway", 
"     Grit", 
"     Gastroenterology", 
"     Garages", 
"     Grading", 
"     Global Teams", 
"     GxP", 
"     Golf ", 
"     Garden", 
"     Gmail", 
"     General Construction", 
"     Geriatric Nursing", 
"     Grills", 
"     Grammar", 
"     Group Policy", 
"     Governance", 
"     Graphics", 
"     Geometry", 
"     Guru", 
"     Glue", 
"     Government Contracting", 
"     Gcs", 
"     General Ledger", 
"     Gaming", 
"     Gourmet", 
"     Graphic Design", 
"     Gross Profit", 
     , 


"    Hardening", 
"     Heavy Lifting", 
"     Healthy Lifestyle", 
"     Hunter", 
"     High Availability", 
"     Higher Education", 
"     Hadoop", 
"     Hudson", 
"     Housewares", 
"     Homeland Security", 
"     HMIs", 
"     Heavy Haul", 
"     Heat", 
"     High Quality Standards", 
"     Health And Safety", 
"     Handle Multiple Priorities", 
"     Hair Styling", 
"     Home Visits", 
"     Hospitality", 
"     HORIZON", 
"     Highways", 
"     Happy Hour", 
"     Home Inspections", 
"     Hyper", 
"     Hematology", 
"     Hawaii", 
"     Helping Clients", 
"     Human Resources", 
"     Hobbies", 
"     Hip", 
"     Handle Confidential Information", 
"     Healthcare Management", 
"     Health And Wellness", 
"     Heating", 
"     Hospitality Industry", 
"     Human Rights", 
"     Horses", 
"     Healing", 
"     Handle Multiple Projects", 
"     Hydraulic Systems", 
"     Health Education", 
"     Home Health Agencies", 
"     Hybrid Cloud", 
"     Heavy Civils", 
"     HRM", 
"     Hot Water", 
"     Hydraulics", 
"     Hemodialysis", 
"     HTML", 
"     Harness", 
"     Headcount", 
"     HVAC", 
"     Health Promotion", 
"     Health Care Professionals", 
"     Home Care", 
"     Humanity", 
"     Healthcare Industry", 
"     Hiring Practices", 
"     Housekeeping", 
"     Hazardous Chemicals", 
"     Hibernate", 
"     Hand Tool", 
"     Human Resource Management", 
"     Hybrid", 
"     HTTP", 
"     Heavy Equipment", 
"     Hands-on Training", 
"     Helpdesk", 
"     HCP", 
"     Health Savings Accounts", 
"     Heavy Duty", 
"     Hooks", 
"     High Level Of Accuracy", 
"     Healthcare Staffing", 
"     Hazardous Materials", 
"     Home Repairs", 
"     Horizontal", 
"     H-1B Visas", 
"     Holding Companies", 
"     Headaches", 
     , 


"    Ingenuity", 
"     IIPP", 
"     Import", 
"     Infrastructure As Code", 
"     ICD-10", 
"     Indiana", 
"     IT Sales", 
"     Information Assurance", 
"     IBM WebSphere", 
"     Ips", 
"     Implementation Plan", 
"     Incident Response", 
"     Intellectual Disabilities", 
"     Intelligence Community", 
"     Instructional", 
"     Imaging", 
"     Intranet", 
"     International Travel", 
"     Integration Testing", 
"     Informational", 
"     Informative", 
"     Integrated Systems", 
"     Intrusion Detection", 
"     Instant", 
"     Infusions", 
"     Independent Living", 
"     Internal Medicine", 
"     Impression", 
"     Interfacing", 
"     IIS", 
"     Illinois", 
"     Internet Access", 
"     IBM DB2", 
"     Idaho", 
"     IPhone", 
"     Internal Controls", 
"     Inspectors", 
"     Inspiration", 
"     Industry Knowledge", 
"     Irrigation", 
"     IT Portfolio", 
"     Infrared", 
"     Investment Strategies", 
"     Instrumentation", 
"     Intakes", 
"     IRS", 
"     Informatica", 
"     Invoicing", 
"     Internal And External Clients", 
"     Infrastructure As Code", 
"     Interpreting", 
"     Iam", 
"     Income Tax", 
"     IBM", 
"     Intellectual", 
"     Incentive Program", 
"     IPad", 
"     Inserts", 
"     ICON", 
"     Instrumental", 
"     Indicators", 
"     Informatics", 
"     Information Technology", 
"     Increase Productivity", 
"     Inspirational", 
"     Identity And Access Management", 
"     ICE", 
"     Ice", 
"     Icd", 
"     IT Operations", 
"     Injections", 
"     Illness", 
"     Internal Customers", 
"     Inventory System", 
"     Ice Cream", 
"     Inventory Accuracy", 
"     Inventory Control", 
"     Internal Audit", 
"     Intelligence", 
"     Illustration", 
     , 

" Java EE", 
" Justice", 
" Juniper", 
" Job Placements", 
" Jewelry", 
" Juice", 
" JSON", 
" JIRA", 
" Juveniles", 
" Jokes", 
" JUnit", 
" JavaScript", 
" Journalism", 
" Jersey", 
" Joints", 
" JCAHO", 
" Java", 
" Jib", 
" Jeans", 
" J2EE", 
" Job Search", 
" Journal Entries", 
" Judicial", 
" JumpStart", 
" Jenkins", 
" Jurisdiction", 
" Juggling", 
" JQuery", 
" Job Posts", 
" Journals", 
" Jets", 
" Joint Ventures", 
" Knee", 
" Knowledge Sharing", 
" Keywords", 
" Key Accounts", 
" Kafka", 
" Kidney", 
" Knowledge Transfer", 
" Knife", 
" Kanban", 
" Kaizen", 
" Knowledge Base", 
" Kiosk", 
" Kenexa", 
" Knowledge Management", 
" Keyboard", 
" Kentucky", 
" Kindergarten", 
" KIVA", 
" Kansas", 
" Key Metrics", 
" Kinetic Modeling", 
" Keyboarding", 
" Key Performance Indicators", 
" Knack", 
" Kubernetes", 
" Laboratory Technicians", 
" LDAP", 
" Lung", 
" Load Balancing", 
" Latin America", 
" Loan Documents", 
" Leave Of Absence", 
" Lynx", 
" Legal Issues", 
" Listings", 
" Law Enforcement", 
" Learning Management", 
" Lettings", 
" Las Vegas", 
" Laboratory Equipment", 
" Learning Management System", 
" Logging", 
" Literature", 
" Labels", 
" Legal Compliance", 
" Leadership Development", 
" Lean Six Sigma", 
" Linux", 
" Lever", 
" Life Support", 
" Latin", 
" Launches", 
" Liability Insurance", 
" Loyalty Programs", 
" Linen", 
" Logistics", 
" Loan Officers", 
" Loan Origination", 
" Lactation", 
" Lifestyle Brands", 
" Leasing", 
" Lodging", 
" Local Food", 
" Luggage", 
" Licensing", 
" Loops", 
" Lifelong Learning", 
" Learning Environment", 
" Lps", 
" Low Voltage", 
" Long Distance", 
" Logistic Support", 
" Life Sciences", 
" Local Government", 
" Lighting", 
" Long-term Care", 
" Linguistics", 
" Lounge", 
" Lean Manufacturing", 
" Licensed Practical Nurse", 
" Local Area Network", 
" Lathe", 
" Landscaping", 
" Litigation", 
" Ledger", 
" Legacy System", 
" Leadership Training", 
" Long Term Acute Care", 
" Light Housekeeping", 
" Learning Styles", 
" LASIK", 
" LaTeX", 
" Logo", 
" Line Management", 
" Lightning", 
" Laser", 
" Louisiana", 
" Life Skills", 
" Logistical", 
" Life Safety", 
" Laundry", 

"    Marketing Strategy", 
"     Manufacturing Processes", 
"     Municipalities", 
"     Managed Services", 
"     Mental Health", 
"     Medical Devices", 
"     Master Data", 
"     Medical Facilities", 
"     Material Handling", 
"     Medical Necessity", 
"     Mention", 
"     MySQL", 
"     Milk", 
"     Mechanisms", 
"     Molding", 
"     Military Personnel", 
"     Myriad", 
"     Mid-Market", 
"     Microsoft Office", 
"     MS SQL", 
"     Mississippi", 
"     Medicare Advantage", 
"     Main Street", 
"     Manual Dexterity", 
"     Medical Office", 
"     Market Analysis", 
"     MEP Design", 
"     Maryland", 
"     Marketing Automation", 
"     Maritime", 
"     Machining", 
"     Microwave", 
"     Metadata", 
"     Multiple Disciplines", 
"     Molecular", 
"     Maker", 
"     Manufacturing Engineering", 
"     Medical Terminology", 
"     Middle School", 
"     Maintenance Management", 
"     Management Development", 
"     Missouri", 
"     Management Professional", 
"     Market Research", 
"     Multi-functional", 
"     Multimedia", 
"     Motion", 
"     Meditech", 
"     Merchant Services", 
"     Material Handling Equipment", 
"     Magics", 
"     Mockup", 
"     Michigan", 
"     Microsoft Windows", 
"     Music", 
"     Microsoft Outlook", 
"     Multiple Projects Simultaneously", 
"     Medical Education", 
"     Masks", 
"     Multiple Sites", 
"     MSDS", 
"     Management Consulting", 
"     Medical-Surgical", 
"     Middle Market", 
"     Mold", 
"     Modeling And Simulation", 
"     Matrix Management", 
"     Mitigation", 
"     Milling", 
"     MongoDB", 
"     Managed Care", 
"     Mobile Apps", 
"     Mirror", 
"     Matlab", 
"     Metal Fabrication", 
"     Microbiology", 
"     Marketing Communications", 
"     Marketing Campaigns", 
"     Mathematics", 
"     Moms", 
     , 

"    North Carolina", 
"     Network Hardware", 
"     New Development", 
"     Nursing Homes", 
"     Nephrology", 
"     Nursing Process", 
"     New Product Development", 
"     Nails", 
"     Numerical Data", 
"     NFPA", 
"     Network Infrastructure", 
"     Neuroscience", 
"     Narrative", 
"     New Trends", 
"     Network Engineering", 
"     NMLS", 
"     New Hire Orientations", 
"     Noc", 
"     Nexus", 
"     Natural Language Processing", 
"     Network Design", 
"     Node.js", 
"     Non-Conforming", 
"     National Accounts", 
"     Notable", 
"     Neurology", 
"     Newspaper", 
"     Nursing", 
"     National Parks", 
"     Nonprofit Organization", 
"     Nuclear", 
"     Network Performance", 
"     Network Devices", 
"     Needs Analysis", 
"     Non-profit", 
"     Nimble", 
"     Network Architecture", 
"     Niches", 
"     Ncs", 
"     Neonatal Intensive Care", 
"     Nurse Practitioners", 
"     National Security", 
"     Network Security", 
"     Nursing Education", 
"     Nursery", 
"     Notification", 
"     Natural Resources", 
"     Nebraska", 
"     Newsletter", 
"     NetSuite", 
"     NoSQL", 
"     Nose", 
"     New Business Opportunities", 
"     Network Administration", 
"     Neck", 
"     North Dakota", 
"     Natural Gas", 
"     Nevada", 
"     Needs Assessment", 
"     Network Technology", 
"     Navigation", 
"     Novel", 
"     New Hire Training", 
"     Nutrition", 
"     Night Vision", 
"     New Business Development", 
"     NIH", 
"     New Concepts", 
"     NEC", 
"     New Jersey", 
"     Navy", 
"     New Mexico", 
"     New Store Openings", 
"     Nephrology Nursing", 
"     New Hampshire", 
"     NCover", 
"     NIST", 
"     New Leads", 
"     NICET", 
"     Net", 
"    Origin", 
"     Occupational Therapy", 
"     Operational Efficiency", 
"     Open Enrollment", 
"     Open Source", 
"     Open Houses", 
"     Oracle Database", 
"     Office Suite", 
"     Office Operations", 
"     Operational Improvement", 
"     Optics", 
"     Operating Models", 
"     Office Procedures", 
"     Orange", 
"     OPM", 
"     ODD", 
"     On Location", 
"     Organizational Development", 
"     Office Software", 
"     Occupancy", 
"     Office Support", 
"     Occupational Safety And Health Administration", 
"     Organization Skills", 
"     Office Managers", 
"     Order Entry", 
"     Omni", 
"     One On One", 
"     Observational", 
"     Occupational Health", 
"     OMB", 
"     Oral Communication", 
"     Overhaul", 
"     Onboarding", 
"     Offshore", 
"     Object-Oriented Design", 
"     Office Of Federal Contract Compliance Programs", 
"     OEMs", 
"     Outings", 
"     Online Marketing", 
"     Oil And Gas", 
"     Operational Activities", 
"     Oregon", 
"     Orchestration", 
"     Outages", 
"     OFCCP", 
"     Oklahoma", 
"     OOPS", 
"     Online Tutoring", 
"     Oncology", 
"     Organizational Structure", 
"     ORM", 
"     Office 365", 
"     Offsets", 
"     Operational Support", 
"     Overflow", 
"     Oil Changes", 
"     Originations", 
"     Order Management", 
"     OASIS", 
"     Oven", 
"     Output", 
"     Operational Risk", 
"     Organics", 
"     On The Job Training", 
"     Oracle", 
"     Operating Budgets", 
"     Object-Oriented Programming", 
"     Order Processing", 
"     Objection", 
"     Oxygen", 
"     Outside Sales", 
"     OOD", 
"     Operating Room", 
"     Object Oriented Design", 
"     Optometry", 
"     Office Equipment", 
"     On-call Support", 
"     Originating", 
"     Object Oriented Programming", 
"     Obstetrics", 
"    Pilot", 
"     Pre-construction", 
"     Psychology", 
"     Pain Management", 
"     PostgreSQL", 
"     Public Works", 
"     Pmi", 
"     Provisioning", 
"     Powder", 
"     Particle", 
"     Project Management Professional", 
"     Proofreading", 
"     Paramedic", 
"     Project Leadership", 
"     Performance Measurement", 
"     PaperLess", 
"     Public Service", 
"     POD", 
"     Personnel Management", 
"     Profitable Growth", 
"     Product Specification", 
"     Phlebotomy", 
"     Patient Outcomes", 
"     Private Schools", 
"     Planograms", 
"     Product Display", 
"     Plumbers", 
"     Pop", 
"     Persistence", 
"     POS", 
"     Programmer", 
"     Product Strategies", 
"     Peoplesoft", 
"     Placing Orders", 
"     Powershell", 
"     PPO", 
"     Prisons", 
"     Pre-employment Testing", 
"     Project Plan", 
"     Professional Manner", 
"     Product Concept", 
"     Project Delivery", 
"     Population Health", 
"     Process Design", 
"     Pricing Strategy", 
"     Printing", 
"     Publications", 
"     Probability", 
"     Peripherals", 
"     Product Offerings", 
"     Point Of Care", 
"     Physics", 
"     Photography", 
"     Profit And Loss Management", 
"     Program Management", 
"     PAD", 
"     Private Duty", 
"     Pumps", 
"     Project Control", 
"     Performance Appraisal", 
"     PAN", 
"     Patrol", 
"     Pharmaceutical Companies", 
"     Professional Driving", 
"     Product Management", 
"     Public Relations", 
"     Punk", 
"     Petty Cash", 
"     Pre-sales", 
"     Pinnacle", 
"     Performance Tuning", 
"     Prescription Drugs", 
"     Passive Income", 
"     Permissions", 
"     Performance Testing", 
"     Physical Plant", 
"     Physiology", 
"     Performance Analysis", 
"     Plumbing", 
" Quality System", 
" Quotas", 
" Quality Management", 
" QuickBooks", 
" QA", 
" Quantitative Analysis", 
" Quality Management System", 
" Quality Improvement", 
" Quick Service", 
" Quotations", 
" Quality Of Service", 
" Quality Patient Care", 
" Quality Assurance", 
" Quality Review", 
" Quality Control", 
"    Rescue", 
"     Relationship Building", 
"     Requirements Gathering", 
"     Restful API", 
"     Records Management", 
"     Rebuilds", 
"     Research And Development", 
"     Remote Access", 
"     Resource Management", 
"     Ranch", 
"     RESTful", 
"     Root Cause Analysis", 
"     Rapid Response", 
"     Retail Banking", 
"     Retirement Savings", 
"     Router", 
"     Reflection", 
"     Restaurant Management", 
"     Restructuring", 
"     Regulatory Submissions", 
"     Requirements Analysis", 
"     Rockets", 
"     RADIUS", 
"     Runway", 
"     Real E", 
"     Relationship Management", 
"     Re-engineering", 
"     Refunds", 
"     Rankings", 
"     Rehabilitation", 
"     Reform", 
"     Radiation Safety", 
"     Reporting Requirements", 
"     Roofs", 
"     Resolving Issues", 
"     Routing Protocol", 
"     Return On Investment", 
"     Real-Time Data", 
"     Risk Management", 
"     Red Hat Enterprise Linux", 
"     Regulatory Agencies", 
"     Rework", 
"     Rts", 
"     Residential Roofing", 
"     Regulatory Affairs", 
"     Residential Treatment", 
"     RDBMS", 
"     Radar", 
"     Reporting Systems", 
"     Rubber", 
"     Revit", 
"     Realistic", 
"     ROIs", 
"     Reverse Logistics", 
"     Racking", 
"     Rolling", 
"     Religion", 
"     Rhythm", 
"     Radio", 
"     RMF", 
"     Routine Maintenance", 
"     Retail Merchandising", 
"     Repository", 
"     Rendering", 
"     Role Modeling", 
"     Retirement Benefits", 
"     Reagents", 
"     RF Scanners", 
"     RHEL", 
"     Refrigeration", 
"     Respiration", 
"     Retail Sales", 
"     Real E Transactions", 
"     Record Of Success", 
"     Radiation", 
"     Rapid Growth", 
"     Relays", 
"     Robotics", 
"     Ratings", 
"     Requirements Management", 
"    Semiconductor", 
"     ServiceNow", 
"     Segmentation", 
"     Systems Development Life Cycle", 
"     Sauces", 
"     Shoes", 
"     Summit", 
"     Swedish", 
"     Sphere", 
"     Successions", 
"     Strategic Leadership", 
"     Sewing", 
"     Stainless Steel", 
"     Store Displays", 
"     Service Quality", 
"     Swing", 
"     Setting Appointments", 
"     SDK", 
"     Systems Engineering", 
"     Sharepoint", 
"     Statistical Analysis", 
"     Security Operations", 
"     Solvents", 
"     Sds", 
"     Shake", 
"     Software Testing", 
"     Subcontracts", 
"     Social Skills", 
"     Spring", 
"     Scenario", 
"     Signal Processing", 
"     Sus", 
"     Supersonic", 
"     Streamline", 
"     Soul", 
"     Supply Management", 
"     SFDC", 
"     Software Engineering", 
"      Laws", 
"     Struts", 
"     Specimen Collection", 
"     Summary Reports", 
"     SEO", 
"     Sandwiches", 
"     Sales Plan", 
"     Satellite", 
"     Standard Operating Procedure", 
"     SVN", 
"     Strategic Planning", 
"     Surface", 
"     Service Improvement", 
"     Structural Engineering", 
"     Systems Analysis", 
"     Shoulder", 
"     Sales Growth", 
"     Synergy", 
"     Sharpen", 
"     Sketches", 
"     Spinal Cord Injury", 
"     Stock Exchange", 
"     Solution Architecture", 
"      Government", 
"     Sales Leadership", 
"     Stressful Situations", 
"     Stored Procedure", 
"     Statistics", 
"     Switchboard", 
"     SALT", 
"     Settlement", 
"     SAINT", 
"     Skype", 
"     Subject Matter Experts", 
"     STAR", 
"     SQL Server Integration Services", 
"     Sketch", 
"     Sales Performance", 
"     Spark", 
"     Startup", 
"     Strengthening", 
"     Sand", 
" Team Management", 
" T-SQL", 
" Traffic Control", 
" Ticketing", 
" Traffic Violations", 
" Trays", 
" Toilets", 
" Talent Management", 
" Torch", 
" Test Reports", 
" TCP/IP", 
" Ticketing Systems", 
" Testers", 
" Tinting", 
" T-Shirts", 
" Transcripts", 
" TFS", 
" Translation", 
" Time And Attendance", 
" Team Leadership", 
" Test Equipment", 
" Twin", 
" Testing Framework", 
" Tobacco", 
" Therapeutic Areas", 
" Team Building", 
" Technical Accounting", 
" TGI", 
" Technological Innovation", 
" Tires", 
" Technical Training", 
" Timing", 
" Taxation", 
" TOW", 
" Titan", 
" Test Cases", 
" Temperature Controlled", 
" Technical Assistance", 
" Tax Planning", 
" Transparency", 
" Terminology", 
" Tax Returns", 
" TWIC Card", 
" Technology Development", 
" Test Strategy", 
" Team Performance", 
" Tissue", 
" Tutoring", 
" Terraform", 
" Technical Design", 
" Technical Analysis", 
" Target Audience", 
" Tablet", 
" Tiling", 
" Toolkit", 
" Technology Consulting", 
" Toddlers", 
" Third-Party Logistics", 
" Technical Reviews", 
" Technical Direction", 
" Tanks", 
" Tape", 
" Technology Trends", 
" Technical Recruiter", 
" Telemetry", 
" Technical Services", 
" Teachable", 
" Television", 
" Technical Presentations", 
" Telemarketing", 
" Technical Ability", 
" TNCC", 
" Tailoring", 
" Technical Documentation", 
" Tracking Systems", 
" Team Development", 
" Task Force", 
" Torque", 
" Team Spirit", 
" Trails", 
"    Unix", 
"     Unify", 
"     Uncertainty", 
"     Unit Testing", 
"     Unit Operations", 
"     Use Case", 
"     User Stories", 
"     User Experience", 
"     Universal Precautions", 
"     UX Design", 
"     Urology", 
"     Updos", 
"     Urban", 
"     Utilities", 
"     Usda", 
"     Ultrafiltration", 
"     Urgent Care", 
"     Ultimate", 
"     User Experience Design", 
"     UX", 
"     Underwriting", 
"     User Interfaces", 
"     Upstream", 
"     User Research", 
"     User Acceptance Testing", 
"     UI Design", 
"     Utilization Management", 
"     Unstructured Data", 
"     User Interface Design", 
"     Unity", 
"     UML", 
"     Utilization Review", 
"     Usability", 
" Vertical", 
" VMware", 
" Vegetables", 
" Vision Insurance", 
" Visual Merchandising", 
" VOIP", 
" Vendor Management", 
" Vulnerability Management", 
" Vaccines", 
" Value-added", 
" Vacuum", 
" Vehicle Maintenance", 
" Video Games", 
" Valve", 
" Venipuncture", 
" Vector", 
" Ventilators", 
" Vinyl", 
" Vulnerability", 
" Version Control", 
" Vascular", 
" Visual Studio", 
" Visual Design", 
" Virus", 
" Vision Care", 
" Ventilation", 
" Vetting", 
" Virginia", 
" Virtualization", 
" Viability", 
" Virtual Machine", 
" Vermont", 
" Visualization", 
" Vital Signs", 
" Valuation", 
" Veterinary Medicine", 
" Visio", 
" Vice Presidents", 
" Vitality", 
" Visual Basic", 
" VPN", 
" Voltage", 
" Vessels", 
" Variance Analysis", 
" Vulnerability Assessment", 
" Velocity", 
" Vitamins", 
" Versioning", 
" Value Proposition", 
" Volunteering", 
" Verification And Validation", 
" Viewpoint", 
" Veterans Affairs", 
" Vaccinations", 
" Vault", 
" VIP", 
" Vibe", 
" Wireless", 
" Wine", 
" Welding", 
" Wyoming", 
" Windows Server", 
" Work Alone", 
" Wellness", 
" Washing", 
" Web Application Development", 
" Wire", 
" Waves", 
" Weddings", 
" Workplace Culture", 
" WordPress", 
" Wireless Technologies", 
" Wildlife", 
" WLL", 
" WebSphere", 
" Web Server", 
" Windows 10", 
" Wineries", 
" Workers Compensation", 
" Warranty", 
" Working With Clients", 
" Warehouse Management System", 
" Wiring Diagram", 
" Waivers", 
" Wastewater", 
" Wrapping", 
" Walton", 
" Water Treatment", 
" Wireframes", 
" Wealth Management", 
" Web Application", 
" White Paper", 
" Wound Care", 
" Working With Children", 
" Wall", 
" Waterfall", 
" WAN", 
" Work At Height", 
" Wax", 
" Warehouse Operations", 
" Wiring", 
" Waxing", 
" Web Pages", 
" Workforce Management", 
" Web Development", 
" Workout", 
" Warehouse Management", 
" Workplace Safety", 
" Word Processing", 
" WRAP", 
" Wi-Fi", 
" Walkways", 
" Web Technologies", 
" Whole Life Insurance", 
" Web Design", 
" Writing", 
" Workable", 
" WiFi", 
" Wholesale", 
" Xpress", 
" XML", 
" Xactimate", 
" X-ray", 
"yoga",
"Android", 
"Java", 
"Kotlin", 
"iOS", 
"Objective C", 
"Swift", 
"Cross Platform", 
"React Native", 
"Flutter", 
"Ionic", 
"Cordova", 
"JavaScript", 
"Ruby Rails", 
"Sinatra", 
"Java ", 
"Play Framework", 
"PHP ", 
"Larvel", 
"Python ", 
"Django", 
"Flask", 
"Scaladevelopers seem to be moving to this", 
"Elixir Phoenix", 
"MySQL", 
"Postgres", 
"SQLite", 
"NoSQL", 
"Mongo", 
"Cassandra", 
"Redis", 
"Neo4J", 
"ReactJS", 
"VueJS", 
"Web Components", 
"AngularJS", 
"Docker", 
"Kubernetes", 
"QFD", 
"Brainstorming", 
"Mind-Map", 
"TRIZ/ARIZ", 
"Innovation algorithms", 

"SAP IDM", 
"SAP HR Functional", 
"SAP HANA Administration", 
"SAP GRC", 
"SAP ABAP On HANA", 
"SAP ABAP", 
"SAP FIORI", 
"SAP BPC", 

"SAP IM", 
"SAP IDM ", 
"SAP IBP ", 
"SAP Hybris ", 
"SAP HR Functional ", 
"SAP HR ", 
"SAP EWM", 
"SAP BODS", 
"SAP HCM ", 
"SAP HANA Administration ", 
"SAP HANA ", 
"SAP GTS ", 
"SAP GRC ", 
"SAP FSCM ", 
"SAP ESS MSS", 
"SAP BODI", 

"SAP FSCD ", 
"SAP PO ", 
"SAP FIORI ", 
"SAP FICO ", 
"SAP PP ", 
"SAP PM ", 
"SAP ERP", 
"SAP BO", 
"SAP PLM ", 
"SAP PI ", 
"SAP OOPS ABAP ", 
"SAP NetWeaver ", 
"SAP MRS ", 
"SAP SRM ", 
"SAP CS", 
"SAP BI ABAP", 
"SAP Vistex ", 
"SAP UI5 ", 
"SAP MM ", 
"SAP CO", 
"SAP HANA ADMINISTRATION", 
"SAP APO", 
"SAP COPA", 
"SAP Basis", 
"SAP SuccessFactors ", 
"SAP SuccessFactors LMS ", 
"SAP Treasury And Risk Management ", 
"SAP Webdynpro ", 
"SAP Workflow ", 
"SAP WM ", 
"SAP CRM", 
"SAP BI", 
"SAP Hybris", 
"SAP ABAP", 
"SAP Simple Finance", 
"SAP FICO", 
"SAP BW On HANA", 
"SAP MDM", 
"SAP BW", 
"SAP Ariba", 
"SAP IS RETAIL", 
"SAP HR", 
"SAP HANA", 
"SAP GTS", 
"SAP GRC", 
"SAP FSCM", 
"SAP Business One", 
"SAP WORKFLOW", 
"Abap", 
"HR", 
"Fico", 
"MM", 
"SD", 
"HANA", 
"Ariba", 
"Hybris", 
"Business one", 
"NetWeaver", 
"BODS", 
"GRC", 
"PP QM", 
"PP/QM", 
"SAP PP ", 
"SAP QM", 
"SAP PP/QM", 
"SAP EP", 
"IS-RE", 
"IS-H", 
"IS-T ", 
"IS-RE", 
"Re-Fx", 
"SAP Re-fx", 
"IS-OIL", 
"IS-A", 
"FS-BP", 
"FS-CMS", 
"FS-PM", 
"FS-RI", 
"FS-ICM", 
"FS-CD", 
"SAP IDM", 
"IDM", 
"FS-PM", 
"SAP-MII", 
"SAP ECM", 
"SAP CRM", 
"SAP Solution Manager", 
"SAP PI", 
"SA EP", 
"ESS", 
"MSS ", 
"SAP HCM", 
"SAP APO ", 
"SAP SCM", 
"SAP FICA", 
"SAP PLM", 
"SAP SRM", 
"SAP EHS", 
"SAP CS", 
"SAP LE", 
"SAP PM", 
"SAP SD", 
"SAP LO", 
"SAP IM", 
"SAP RE", 
"SAP TR", 
"SAP FI", 
"SAP CO", 
"SAP FI CO",
"Rational Rose", 
" MS Visio", 
" NetBeans", 
"Open Office Draw", 
"Star UML", "Together", 
"matrix", 
"Database modeling tools", 
"MySQL Workbench", 
"DbVisualizer", 
"Oracle ", 
"SQLDeveloper", 
" Toad", 
"Project planning and management", 
"Jira", 
" Confluence", 
"MS Project", 
" ScrumDesk", 
"Effort estimation", 
"Top-down", 
" PERT", 
"Risk identification", 
" evaluation and minimization", 
"Software-FMEA", 
"Software development methodologies", 
"Agile", 
" Scrum", 
" Kamban", 
" Scrumban", 
" RUP", 
" DSDM", 
" etc.", 
"Testing", 
"Testing tools ", 
"frameworks", 
"Selenium", 
" Protractor", 
" Ranorex", 
" JMeter", 
" JBehave", 
" Testing Anywhere", 
" WebUI Test Studio", 
" TestComplete", 
" SOAP UI", 
" EasyMock", 
" Mockito", 
" jMock", 
" WebUI test Tool", 
" TCMS", 
" Cucumber", 
" ProjectLocker", 
"Issue management", 
"JIRA", 
" Redmine", 
" Rally", 
" Trac", 
" ActiveCollab", 
" Rational ClearQuest", 
" Bugzilla", 
" Bugzero", 
" Remedy", 
" TestLink", 
" TestTrack", 
"UX/UI Design", 
"UX", 

"Axure", 

"Adobe XD", 

" Invision", 

" Moqups", 
"UI", 
"graphic", 


"Adobe Photoshop", 

" Adobe Illustrator", 

" Zeplin", 

" Adobe XD", 

"Programming languages:", 

"Java", 

" PHP", 

" Ruby", 

" C#", "C / C++", 

" SQL", 

" PL/SQL", 

" ASP .NET", 

" Objective-C", 

" Visual Basic", 

"Technologies", 

" libraries ", 

"frameworks", 



"Java", 

"JEE", 

" Spring", 

"Spring Security", 

" Spring Boot", 

" JPA", 

" Hibernate", 

" Flyway", 

" Swing", 

" JSF", 

" Apache Wicket", 

" Velocity", 

" GWT", 

" JXL", 

"Oracle Portal", 
"PHP", 

"CodeIgniter", 

" Laravel", 

"Symphony", 

"Zend", 

" Yii", 

"WordPress", 

"Joomla", 

"Drupal", 

"Magento", 

"Prestashop", 
"C#", 

"Microsoft Visual Studio", 

"Telerik Framework", 

"Entity Framework", 

"ASP Web API", 

" WinForms", 

"ASP.NET MVC", 

"Neodynamic SDK", 
".NET", 

"ASP.NET", 

"Visual Basic", 
"Ruby", 

"Rails", 

"Capistrano", 

"RMagick", 

"Geokit", 

"RSpec", 
"C++", 

"Windows API", 

"ActiveX", 

"XCode", 

"wxWidgets", 

"STL", 

"WinDDK", 

"Qt Framework", 

"Microsoft CRM", 
"UI ", 

" Web development frameworks", 

"Angular", 

"React", 

"VueJS", 
"Ajax ", 

"JavaScript", 

"NodeJS", 

"JQuery", 

"ExtJS", 

"JSON", 

"MooTools", 

"ASP.NET Ajax control Toolkit", 

"Dojo", 


"Web technologies", 

"Bootstrap", 

"Typescript", 

"D3.js", 

"XHTML", 

"HTML5", 

"XML", 

"XSL", 

"XPath", 

"XQuery", 

"SAX", "DOM", 

"StAX", 

"TinyMCE", 

" JW Player", 

"Highcharts", 

"amCharts", 

"Modernizr", 

"Oauth2 security", 

"Omniauth security", 
"Mobile", 

"React Native", 

" PhoneGap", 

" iPhone SDK", 

"Android SDK", 

"Xamarin", 

"JQuery ", 

"Mobile", 
"BI", 

"Tableau", 

" Pentaho Business Inteligence", 

"Crystal Reports", 
"Web Services", 

"REST API", 

"Apache CXF", 

"Axis", 

"SOAP", 

"WSDL", 

"JAXB", 

"JAX-WS", 
"Messaging Middleware", 

"Apache Kafka", 

"ActiveMQ", 

" IBM MQ Series", 

"IDE", 

"Eclipse", 

"Idea", 

"MS Visual Studio", 

"Aptana Studio", 

" XCode", 

"Versioning Control", 

"Git", 

"SVN", 

"Rational ClearCase", 

"Rational Synergy", 

"MS Visual Source Safe", 

"MavenAnt", 

"Continuous integration", 

"Jenkins", 

"Bamboo", 

"Databases", 

"Data storages", 

"MySQL", 

"PostgreSQL", 

"Oracle", 

"MS SQL Server", 

"Derby", 

"Lucene", 

"SOLR", 

"ElasticSearch", 

"MongoDB", 

"LDAP", 

"Application and web servers:", 

"Apache Tomcat", 

"JBoss AS", 

"Jetty", 

"IBM WebShere", 

"Oracle Application Server", 

" WebLogic", 

"Windows Server IIS", 

" Nginx", 

"Cloud computing", 

"Amazon Web Services", 

"Azure", 

" private cloud", 

"Enterprise Service Bus", 

"BizTalk", 

"Sales Force Management:", 

"SalesForce", 

"Cloud"




]

export const jobroles=[
     "Android Engineer",
"Backend Engineer",
"Data Engineer",
"DevOps",
"Front-end Engineer",
"Full Stack Engineer",
"IOS Engineer",
"QA/SDET",
"Data Scientist",
"Engineering Manager",
"Product Manager",
"others"
]